const supportedLanguages = ["en", "es", "fr", "de", "pt", "sr", "ja"];

function getLanguageName(languageCode: string) {
    switch (languageCode) {
        case 'en': return 'English';
        case 'es': return 'Español';
        case 'fr': return 'Français';
        case 'de': return 'Deutsch';
        case 'pt': return 'Português';
        case 'sr': return 'Srpski';
        case 'ja': return '日本語';
        default: return languageCode;
    }
}

const translations = {
    en: {
        // Generic
        back: 'Back',
        cancel: 'Cancel',
        delete: 'Delete',
        confirm: 'Confirm',
        clear: 'Clear',
        details: 'Details',
        noDetailsFound: 'No details found.',
        oops: 'Oops!',
        screenDoesntExist: 'This screen doesn\'t exist.',
        goToHomeScreen: 'Go to home screen!',
        ignore: 'Ignore',
        reset: 'Reset',
        apply: 'Apply',

        // Discover screen
        discover: 'Discover',
        discoverSubtitle: 'Results related to ',
        promptPlaceholder: "Enter any topic, theme, or lyrics...",
        topResults: 'Top Results',
        filters: 'Filter Hymnals',
        allHymnals: 'All Hymnals',

        // Broadcast screen
        broadcast: 'Broadcast',
        selectedChurch: 'Selected Church',
        actions: 'ACTIONS',
        setSongNumber: 'Set Song Number',
        setBibleReading: 'Set Bible Reading',
        clearScreen: 'Clear Screen',
        logOut: 'Log Out',

        // Search and Bookmarks screen
        search: 'Search',
        bookmarks: 'Bookmarks',
        featured: 'Featured Songs',
        recent: 'Recent Searches',
        clearAll: 'Clear All',
        clearHistory: 'Clear History',
        clearHistoryMessage: 'You cannot undo this action',
        remove: 'Remove',
        removeMessage: 'Are you sure you want to remove this bookmark?',

        // Home screen
        home: 'Home',
        noHymnals: 'No Hymnals',
        addHymnal: 'Add Hymnal',
        deleteAlertTitle: 'Delete ',
        deleteAlertMessage: 'You can always download the hymnal again later.',

        // Settings screen
        settings: 'Settings',
        info: 'INFO',
        appVersion: 'App Version',

        // Help screen
        help: 'Help',
        general: 'GENERAL',
        reportBug: 'Report a Bug',
        requestBook: 'Request a Book or Feature',
        privacyPolicy: 'Privacy Policy',
        debug: 'DEBUG',
        clearCache: 'Clear Cache',
        deleteHymnals: 'Delete All Hymnals',
        clearCacheConfirmation: 'Clear Cache?',
        deleteHymnalsConfirmation: 'Delete All Hymnals?',
        clearCacheConfirmationMessage: 'This will delete all cached files created by the app.',
        deleteHymnalsConfirmationMessage: 'This will delete all hymnals currently downloaded.',
        posthogOptOut: 'Opt Out of Data Collection',
        posthogOptIn: 'Opt In to Data Collection',
        posthogOptOutConfirmation: 'Opt Out of Data Collection?',
        posthogOptOutConfirmationMessage: 'This will opt you out of data collection. You can opt in again at any time.',

        // Preferences screen
        preferences: 'Preferences',
        accessibilityAndLanguage: 'ACCESSIBILITY & LANGUAGE',
        legacyNumberSelection: 'Legacy Number Selection',
        language: 'Language',
        appearance: 'APPEARANCE',
        theme: 'Theme',
        darkMode: 'Dark Mode',
        lightMode: 'Light Mode',
        systemDefault: 'System Default',
        other: 'Other',
        invertSheetMusic: 'Invert Notation Colors',

        // Hymnal menu
        sortingLabel: 'Sorting Options',
        numerical: 'Numerical',
        alphabetical: 'Alphabetical',
        topical: 'Topical',
        deleteHymnal: 'Delete Hymnal',

        // Display screen
        notes: 'Notes',
        piano: 'Piano',
        all: 'All',
        removeBookmark: 'Remove Bookmark',
        saveBookmark: 'Save as Bookmark',
        share: 'Share',
        reportIssueMessage: 'Report an issue for this song?',
        reportIssue: 'Report Issue',
        reportIssueSuccess: 'Issue reported successfully',
        reportIssueFailure: 'Failed to report issue',

        // Hymnal Importer screen
        addHymnalSubtitle: 'Download hymnals to access them offline.',
        verifying: 'Verifying...',
        size: 'Size',
        progress: 'Progress',
        failedToLoadHymnals: 'Failed to load Hymnals',
        failedToLoadHymnalsMessage: 'Please check your internet connection and try again.',
        retry: 'Retry',
        verificationFailed: 'Verification Failed',
        verificationFailedMessage: 'Some files were unable to download properly. Please try again.',
        ok: 'OK',
        startingDownload: 'Starting download...',
    },
    es: {
        // Generic
        back: 'Atrás',
        cancel: 'Cancelar',
        delete: 'Borrar',
        confirm: 'Confirmar',
        clear: 'Limpiar',
        details: 'Detalles',
        noDetailsFound: 'No se encontraron detalles.',
        oops: '¡Ay!',
        screenDoesntExist: 'Esta pantalla no existe.',
        goToHomeScreen: '¡Ir a la pantalla de inicio!',
        ignore: 'Ignorar',
        reset: 'Restablecer',
        apply: 'Aplicar',

        // Search and Bookmarks screen
        search: 'Buscar',
        bookmarks: 'Marcadores',
        featured: 'Canciones Destacadas',
        recent: 'Búsquedas Recientes',
        clearAll: 'Limpiar Todo',
        clearHistory: 'Limpiar Historial',
        clearHistoryMessage: 'No se puede deshacer esta acción',
        remove: 'Eliminar',
        removeMessage: '¿Estás seguro de querer eliminar este marcador?',

        discover: 'Descubrir',
        discoverSubtitle: 'Resultados relacionados con ',
        promptPlaceholder: "Introduce cualquier tema, asunto o letra...",
        topResults: 'Mejores Resultados',
        filters: 'Filtrar Himnarios',
        allHymnals: 'Todos los Himnarios',

        home: 'Inicio',
        noHymnals: 'No hay Himnarios',
        addHymnal: 'Agregar Himnarios',
        deleteAlertTitle: 'Borrar ',
        deleteAlertMessage: 'Siempre puedes descargar el himnario de nuevo más tarde.',

        settings: 'Configuración',
        info: 'INFORMACIÓN',
        appVersion: 'Versión de la aplicación',

        help: 'Ayuda',
        general: 'GENERAL',
        reportBug: 'Reportar un Bug',
        requestBook: 'Solicitar un Libro o Característica',
        privacyPolicy: 'Política de Privacidad',
        debug: 'DEBUG',
        clearCache: 'Limpiar Caché',
        deleteHymnals: 'Eliminar Todos los Hymnals',
        clearCacheConfirmation: 'Limpiar Caché?',
        deleteHymnalsConfirmation: 'Eliminar Todos los Hymnals?',
        clearCacheConfirmationMessage: 'Esto eliminará todos los archivos caché creados por la aplicación.',
        deleteHymnalsConfirmationMessage: 'Esto eliminará todos los hymnals actualmente descargados.',
        posthogOptOut: 'Desactivar la recopilación de datos',
        posthogOptIn: 'Activar la recopilación de datos',
        posthogOptOutConfirmation: '¿Desactivar la recopilación de datos?',
        posthogOptOutConfirmationMessage: 'Esto desactivará la recopilación de datos. Puede activarla de nuevo en cualquier momento.',

        preferences: 'Preferencias',
        accessibilityAndLanguage: 'ACCESIBILIDAD Y IDIOMA',
        legacyNumberSelection: 'Selección de Número Antigua',
        language: 'Idioma',
        appearance: 'APARIENCIA',
        theme: 'Tema',
        darkMode: 'Modo Oscuro',
        lightMode: 'Modo Claro',
        systemDefault: 'Sistema por Defecto',
        other: 'Otro',
        invertSheetMusic: 'Invertir Colores de Notación',

        sortingLabel: 'Opciones de Ordenamiento',
        numerical: 'Numérico',
        alphabetical: 'Alfabético',
        topical: 'Tópico',
        deleteHymnal: 'Borrar Himnario',

        notes: 'Notas',
        piano: 'Piano',
        all: 'Todas',
        removeBookmark: 'Eliminar Marcador',
        saveBookmark: 'Guardar como Marcador',
        share: 'Compartir',
        reportIssue: 'Reportar Problema',
        reportIssueSuccess: 'Problema reportado correctamente',
        reportIssueFailure: 'Error al reportar el problema',

        // Hymnal Importer screen
        addHymnalSubtitle: 'Descarga himnarios para acceder sin conexión.',
        verifying: 'Verificando...',
        size: 'Tamaño',
        progress: 'Progreso',
        failedToLoadHymnals: 'No se pudieron cargar los himnarios',
        failedToLoadHymnalsMessage: 'Por favor, verifica tu conexión a internet y vuelve a intentarlo.',
        retry: 'Reintentar',
        verificationFailed: 'Verificación Fallida',
        verificationFailedMessage: 'Algunos archivos no pudieron descargarse correctamente. Por favor, intenta nuevamente.',
        ok: 'OK',
        startingDownload: 'Iniciando descarga...',
    },
    fr: {
        // Generic
        back: 'Retour',
        cancel: 'Annuler',
        delete: 'Supprimer',
        confirm: 'Confirmer',
        clear: 'Effacer',
        details: 'Détails',
        noDetailsFound: 'Aucun détail trouvé.',
        oops: 'Oups!',
        screenDoesntExist: 'Cette écran n\'existe pas.',
        goToHomeScreen: 'Retour à l\'écran d\'accueil !',
        ignore: 'Ignorer',
        reset: 'Réinitialiser',
        apply: 'Appliquer',

        // Search and Bookmarks screen
        search: 'Rechercher',
        bookmarks: 'Marque-pages',
        featured: 'Chants Destacés',
        recent: 'Recherches Récentes',
        clearAll: 'Tout Effacer',
        clearHistory: 'Effacer l\'Historique',
        clearHistoryMessage: 'Vous ne pouvez pas annuler cette action',
        remove: 'Supprimer',
        removeMessage: 'Êtes-vous sûr de vouloir supprimer ce marque-page ?',

        discover: 'Découvrir',
        discoverSubtitle: 'Résultats liés à ',
        promptPlaceholder: "Entrez un sujet, un thème ou des paroles...",
        topResults: 'Meilleurs Résultats',
        filters: 'Filtrer les Hymnaires',
        allHymnals: 'Tous les Hymnaires',

        home: 'Accueil',
        noHymnals: 'Aucun Livre de Hymnes',
        addHymnal: 'Ajouter un Livre de Hymnes',
        deleteAlertTitle: 'Supprimer ',
        deleteAlertMessage: 'Vous pouvez toujours télécharger le livre de hymnes plus tard.',

        settings: 'Paramètres',
        info: 'INFORMATIONS',
        appVersion: 'Version de l\'application',

        help: 'Aide',
        general: 'GÉNÉRAL',
        reportBug: 'Signaler un Bug',
        requestBook: 'Demander un Livre ou une Fonctionnalité',
        privacyPolicy: 'Politique de Confidentialité',
        debug: 'DEBUG',
        clearCache: 'Effacer le Cache',
        deleteHymnals: 'Supprimer Tous les Hymnals',
        clearCacheConfirmation: 'Effacer le Cache?',
        deleteHymnalsConfirmation: 'Supprimer Tous les Hymnals?',
        clearCacheConfirmationMessage: 'Cela supprimera tous les fichiers mis en cache créés par l\'application.',
        deleteHymnalsConfirmationMessage: 'Cela supprimera tous les hymnals actuellement téléchargés.',
        posthogOptOut: 'Désactiver la collecte de données',
        posthogOptIn: 'Activer la collecte de données',
        posthogOptOutConfirmation: 'Désactiver la collecte de données?',
        posthogOptOutConfirmationMessage: 'Cela désactivera la collecte de données. Vous pouvez l\'activer à nouveau à tout moment.',


        preferences: 'Préférences',
        accessibilityAndLanguage: 'ACCESSIBILITÉ ET LANGUE',
        legacyNumberSelection: 'Sélection de Numéro Ancien',
        language: 'Langue',
        appearance: 'APPARIENCE',
        theme: 'Thème',
        darkMode: 'Mode Sombre',
        lightMode: 'Mode Clair',
        systemDefault: 'Système par Défaut',
        other: 'Autre',
        invertSheetMusic: 'Inverser les Couleurs de la Notation',

        sortingLabel: 'Options de Tri',
        numerical: 'Numérique',
        alphabetical: 'Alphabétique',
        topical: 'Topique',
        deleteHymnal: 'Supprimer le Livre de Hymnes',

        notes: 'Notes',
        piano: 'Piano',
        all: 'Toutes',
        removeBookmark: 'Supprimer le Marque-page',
        saveBookmark: 'Enregistrer comme Marque-page',
        share: 'Partager',
        reportIssue: 'Signaler un Problème',
        reportIssueSuccess: 'Problème signalé avec succès',
        reportIssueFailure: 'Échec du signalement du problème',

        // Hymnal Importer screen
        addHymnalSubtitle: 'Téléchargez les hymnaires pour les accéder hors ligne.',
        verifying: 'Vérification...',
        size: 'Taille',
        progress: 'Progression',
        failedToLoadHymnals: 'Échec du chargement des hymnaires',
        failedToLoadHymnalsMessage: 'Veuillez vérifier votre connexion internet et réessayer.',
        retry: 'Réessayer',
        verificationFailed: 'Échec de la vérification',
        verificationFailedMessage: 'Certains fichiers n\'ont pas pu être téléchargés correctement. Veuillez réessayer.',
        ok: 'D\'accord',
        startingDownload: 'Démarrage de la téléchargement...',
    },
    de: {
        // Generic
        back: 'Zurück',
        cancel: 'Stornieren',
        delete: 'Löschen',
        confirm: 'Bestätigen',
        clear: 'Löschen',
        details: 'Details',
        noDetailsFound: 'Keine Details gefunden.',
        oops: 'Hoppla!',
        screenDoesntExist: 'Diese Seite existiert nicht.',
        goToHomeScreen: 'Zurück zur Startseite!',
        ignore: 'Ignorieren',
        reset: 'Zurücksetzen',
        apply: 'Anwenden',

        // Search and Bookmarks screen
        search: 'Suchen',
        bookmarks: 'Lesezeichen',
        featured: 'Vorgestellte Lieder',
        recent: 'Kürzlich durchsucht',
        clearAll: 'Alles Löschen',
        clearHistory: 'Löschen',
        clearHistoryMessage: 'Sie können diese Aktion nicht rückgängig machen',
        remove: 'Löschen',
        removeMessage: 'Sind Sie sicher, dass Sie dieses Lesezeichen entfernen möchten?',

        discover: 'Entdecken',
        discoverSubtitle: 'Ergebnisse zu ',
        promptPlaceholder: "Gib ein Thema, Motiv oder Liedtext ein...",
        topResults: 'Top-Ergebnisse',
        filters: 'Gesangbücher filtern',
        allHymnals: 'Alle Gesangbücher',

        home: 'Startseite',
        noHymnals: 'Keine Gesangbücher',
        addHymnal: 'Gesangbuch hinzufügen',
        deleteAlertTitle: 'Löschen ',
        deleteAlertMessage: 'Sie können das Gesangbuch später jederzeit erneut herunterladen.',

        settings: 'Einstellungen',
        info: 'INFORMATIONEN',
        appVersion: 'App-Version',

        help: 'Hilfe',
        general: 'ALLGEMEIN',
        reportBug: 'Fehler melden',
        requestBook: 'Buch oder Funktion anfragen',
        privacyPolicy: 'Datenschutzrichtlinie',
        debug: 'Debuggen',
        clearCache: 'Cache löschen',
        deleteHymnals: 'Alle Hymnals löschen',
        clearCacheConfirmation: 'Cache löschen?',
        deleteHymnalsConfirmation: 'Alle Hymnals löschen?',
        clearCacheConfirmationMessage: 'Dies wird alle zwischengespeicherten Dateien löschen, die von der App erstellt wurden.',
        deleteHymnalsConfirmationMessage: 'Dies wird alle derzeit heruntergeladenen Hymnals löschen.',
        posthogOptOut: 'Datensammlung deaktivieren',
        posthogOptIn: 'Datensammlung aktivieren',
        posthogOptOutConfirmation: 'Datensammlung deaktivieren?',
        posthogOptOutConfirmationMessage: 'Dies deaktiviert die Datensammlung. Sie können sie jederzeit wieder aktivieren.',

        preferences: 'Einstellungen',
        accessibilityAndLanguage: 'ZUGANG & SPRACHE',
        legacyNumberSelection: 'Veraltete Zahlauswahl',
        language: 'Sprache',
        appearance: 'ERSCHEINUNGSBILD',
        theme: 'Thema',
        darkMode: 'Dunkelmodus',
        lightMode: 'Hellmodus',
        systemDefault: 'Systemstandard',
        other: 'Andere',
        invertSheetMusic: 'Notensystem invertieren',

        sortingLabel: 'Sortieroptionen',
        numerical: 'Numerisch',
        alphabetical: 'Alphabetisch',
        topical: 'Thematisch',
        deleteHymnal: 'Gesangbuch löschen',

        notes: 'Noten',
        piano: 'Piano',
        all: 'Alle',
        removeBookmark: 'Löschen',
        saveBookmark: 'Speichern als Lesezeichen',
        share: 'Teilen',
        reportIssue: 'Problem melden',
        reportIssueSuccess: 'Problem erfolgreich gemeldet',
        reportIssueFailure: 'Fehler beim Melden des Problems',

        // Hymnal Importer screen
        addHymnalSubtitle: 'Lade Hymnals herunter, um sie offline verfügbar zu machen.',
        verifying: 'Verifizieren...',
        size: 'Größe',
        progress: 'Fortschritt',
        failedToLoadHymnals: 'Hymnals konnten nicht geladen werden',
        failedToLoadHymnalsMessage: 'Bitte überprüfe deine Internetverbindung und versuche es erneut.',
        retry: 'Erneut versuchen',
        verificationFailed: 'Verifizierung fehlgeschlagen',
        verificationFailedMessage: 'Einige Dateien konnten nicht ordnungsgemäß heruntergeladen werden. Bitte versuche es erneut.',
        ok: 'OK',
        startingDownload: 'Herunterladen gestartet...',
    },
    sr: {
        // Generic
        back: 'Nazad',
        cancel: 'Otkaži',
        delete: 'Obriši',
        confirm: 'Potvrdi',
        clear: 'Očisti',
        details: 'Detalji',
        noDetailsFound: 'Nema detalja pronađen.',
        oops: 'Ups!',
        screenDoesntExist: 'Ova stranica ne postoji.',
        goToHomeScreen: 'Vrati se na početnu stranicu!',
        ignore: 'Zanemariti',
        reset: 'Poništi',
        apply: 'Primeni',

        // Search and Bookmarks screen
        search: 'Pretraži',
        bookmarks: 'Zabilježi',
        featured: 'Predstavljeni Pjesmi',
        recent: 'Nedavne Pretrage',
        clearAll: 'Očisti Sve',
        clearHistory: 'Očisti Historijat',
        clearHistoryMessage: 'Ne možete vratiti ovu akciju',
        remove: 'Obriši',
        removeMessage: 'Jeste li sigurni da želite obrisati ovu zabilješku?',

        discover: 'Otkrij',
        discoverSubtitle: 'Rezultati povezani sa ',
        promptPlaceholder: "Unesite bilo koju temu, motiv ili tekst pesme...",
        topResults: 'Najbolji Rezultati',
        filters: 'Filtriraj Himnare',
        allHymnals: 'Svi Himnari',

        home: 'Početna',
        noHymnals: 'Nema himnala',
        addHymnal: 'Dodajte himnala',
        deleteAlertTitle: 'Obriši ',
        deleteAlertMessage: 'Možete u ljubom trenutku ponovo preuzeti himnolog.',

        settings: 'Postavke',
        info: 'INFORMACIJE',
        appVersion: 'Verzija aplikacije',

        help: 'Pomoć',
        general: 'OPŠTE',
        reportBug: 'Prijavi grešku',
        requestBook: 'Zatražite knjigu ili funkciju',
        privacyPolicy: 'Politika privatnosti',
        debug: 'Otlaži',
        clearCache: 'Očisti keš',
        deleteHymnals: 'Obriši sve himnarije',
        clearCacheConfirmation: 'Očisti keš?',
        deleteHymnalsConfirmation: 'Obriši sve himnarije?',
        clearCacheConfirmationMessage: 'Ovo će obrisati sve keš fajlove koje je napravila aplikacija.',
        deleteHymnalsConfirmationMessage: 'Ovo će obrisati sve himnarije koje su trenutno preuzete.',
        posthogOptOut: 'Deaktivirati prikupljanje podataka',
        posthogOptIn: 'Aktivirati prikupljanje podataka',
        posthogOptOutConfirmation: 'Deaktivirati prikupljanje podataka?',
        posthogOptOutConfirmationMessage: 'Ovo će deaktivirati prikupljanje podataka. Možete ih ponovno aktivirati u bilo kojem trenutku.',

        preferences: 'Postavke',
        accessibilityAndLanguage: 'PRISTUP I JEZIK',
        legacyNumberSelection: 'Starostručna Izbora',
        language: 'Jezik',
        appearance: 'APARATURA',
        theme: 'Tema',
        darkMode: 'Tamni Modus',
        lightMode: 'Svijetli Modus',
        systemDefault: 'Sistem Standard',
        other: 'Ostalo',
        invertSheetMusic: 'Invertir Notación',

        sortingLabel: 'Sortiranje',
        numerical: 'Numerički',
        alphabetical: 'Abecedni',
        topical: 'Tematički',
        deleteHymnal: 'Obriši himnolog',

        notes: 'Notatke',
        piano: 'Piano',
        all: 'Sve',
        removeBookmark: 'Ukloni Bookmark',
        saveBookmark: 'Sačuvaj kao Bookmark',
        share: 'Podelite',
        reportIssue: 'Prijavite Problem',
        reportIssueSuccess: 'Problem uspešno prijavljen',
        reportIssueFailure: 'Greška pri prijavi problema',
        // Hymnal Importer screen
        addHymnalSubtitle: 'Preuzmite himnale za dostupnost offline.',
        verifying: 'Verifikacija...',
        size: 'Veličina',
        progress: 'Napredak',
        failedToLoadHymnals: 'Hymnale nisu mogli biti učitani',
        failedToLoadHymnalsMessage: 'Provjerite svoju internet konekciju i pokušajte ponovno.',
        retry: 'Pokušaj ponovno',
        verificationFailed: 'Verifikacija nije uspjela',
        verificationFailedMessage: 'Neki fajlovi nisu mogli biti preuzeti. Pokušajte ponovno.',
        ok: 'U redu',
        startingDownload: 'Preuzimanje započelo...',
    },
    ja: {
        // Generic
        back: '戻る',
        cancel: 'キャンセル',
        delete: '削除',
        confirm: '確認',
        clear: 'クリア',
        details: '詳細',
        noDetailsFound: '詳細が見つかりません。',
        oops: 'あっ！',
        screenDoesntExist: 'この画面は存在しません。',
        goToHomeScreen: 'ホーム画面に戻る！',
        ignore: '無視',
        reset: 'リセット',
        apply: '適用',

        // Search and Bookmarks screen
        search: '検索',
        bookmarks: 'ブックマーク',
        featured: 'おすすめの曲',
        recent: '最近の検索',
        clearAll: 'すべてクリア',
        clearHistory: '履歴をクリア',
        clearHistoryMessage: 'この操作は元に戻せません',
        remove: '削除',
        removeMessage: 'このブックマークを削除してもよろしいですか？',

        discover: '発見',
        discoverSubtitle: '関連する結果: ',
        promptPlaceholder: "トピック、テーマ、歌詞を入力...",
        topResults: 'トップ結果',
        filters: '聖歌集を絞り込む',
        allHymnals: 'すべての聖歌集',

        home: 'ホーム',
        noHymnals: '賛美歌集なし',
        addHymnal: '賛美歌集を追加',
        deleteAlertTitle: '削除 ',
        deleteAlertMessage: '賛美歌集はいつでも再ダウンロードできます。',

        settings: '設定',
        info: '情報',
        appVersion: 'アプリケーションバージョン',

        help: 'ヘルプ',
        general: '一般',
        reportBug: 'バグを報告',
        requestBook: '本または機能をリクエスト',
        privacyPolicy: 'プライバシーポリシー',
        debug: 'デバッグ',
        clearCache: 'キャッシュをクリア',
        deleteHymnals: '賛美歌集を削除',
        clearCacheConfirmation: 'キャッシュをクリア?',
        deleteHymnalsConfirmation: '賛美歌集を削除?',
        clearCacheConfirmationMessage: 'これはアプリが作成したキャッシュファイルをすべて削除します。',
        deleteHymnalsConfirmationMessage: 'これは現在ダウンロードされている賛美歌集をすべて削除します。',
        posthogOptOut: 'データ収集をオフにする',
        posthogOptIn: 'データ収集をオンにする',
        posthogOptOutConfirmation: 'データ収集をオフにする?',
        posthogOptOutConfirmationMessage: 'これはデータ収集をオフにします。いつでもオンにすることができます。',

        preferences: '設定',
        accessibilityAndLanguage: 'アクセシビリティと言語',
        legacyNumberSelection: '旧番号選択',
        language: '言語',
        appearance: '外観',
        theme: 'テーマ',
        darkMode: 'ダークモード',
        lightMode: 'ライトモード',
        systemDefault: 'システムデフォルト',
        other: 'その他',
        invertSheetMusic: 'ノートの色を反転',

        sortingLabel: '並べ替えオプション',
        numerical: '数字順',
        alphabetical: 'アルファベット順',
        topical: 'トピック順',
        deleteHymnal: '賛美歌を削除する',

        notes: 'ノート',
        piano: 'ピアノ',
        all: 'すべて',
        removeBookmark: 'ブックマークを削除',
        saveBookmark: 'ブックマークとして保存',
        share: '共有',
        reportIssue: '問題を報告',
        reportIssueSuccess: '問題が報告されました',
        reportIssueFailure: '問題の報告に失敗しました',
        // Hymnal Importer screen
        addHymnalSubtitle: 'オフラインで賛美歌集にアクセスするためにダウンロードします。',
        verifying: '確認中...',
        size: 'サイズ',
        progress: '進行状況',
        failedToLoadHymnals: '賛美歌集を読み込めませんでした',
        failedToLoadHymnalsMessage: 'インターネット接続を確認して、もう一度お試しください。',
        retry: '再試行',
        verificationFailed: '確認に失敗しました',
        verificationFailedMessage: '一部のファイルが正しくダウンロードされませんでした。もう一度お試しください。',
        ok: 'わかった',
        startingDownload: 'ダウンロードを開始しています...',
    },
    pt: {
        // Generic
        back: 'Voltar',
        cancel: 'Cancelar',
        delete: 'Deletar',
        confirm: 'Confirmar',
        clear: 'Limpar',
        details: 'Detalhes',
        noDetailsFound: 'Nenhum detalhe encontrado.',
        oops: 'Ops!',
        screenDoesntExist: 'Esta tela não existe.',
        goToHomeScreen: 'Voltar para a tela inicial!',
        ignore: 'Ignorar',
        reset: 'Redefinir',
        apply: 'Aplicar',

        // Search and Bookmarks screen
        search: 'Pesquisar',
        bookmarks: 'Marcadores',
        featured: 'Músicas Destacadas',
        recent: 'Pesquisas Recentes',
        clearAll: 'Limpar Tudo',
        clearHistory: 'Limpar Histórico',
        clearHistoryMessage: 'Você não pode desfazer esta ação',
        remove: 'Remover',
        removeMessage: 'Tem certeza que deseja remover este marcador?',

        discover: 'Descobrir',
        discoverSubtitle: 'Resultados relacionados a ',
        promptPlaceholder: "Digite qualquer assunto, tema ou letra...",
        topResults: 'Principais Resultados',
        filters: 'Filtrar Hinários',
        allHymnals: 'Todos os Hinários',

        home: 'Início',
        noHymnals: 'Sem hinários',
        addHymnal: 'Adicionar Hinário',
        deleteAlertTitle: 'Deletar ',
        deleteAlertMessage: 'Você pode sempre baixar o hinário novamente mais tarde.',

        settings: 'Preferências',
        info: 'INFORMAÇÕES',
        appVersion: 'Versão do aplicativo',

        help: 'Ajuda',
        general: 'GERAL',
        reportBug: 'Relatar Bug',
        requestBook: 'Solicitar Livro ou Funcionalidade',
        privacyPolicy: 'Política de Privacidade',
        debug: 'DEBUG',
        clearCache: 'Limpar Cache',
        deleteHymnals: 'Deletar Todos os Hymnals',
        clearCacheConfirmation: 'Limpar Cache?',
        deleteHymnalsConfirmation: 'Deletar Todos os Hymnals?',
        clearCacheConfirmationMessage: 'Isso deletará todos os arquivos em cache criados pela aplicação.',
        deleteHymnalsConfirmationMessage: 'Isso deletará todos os hymnals atualmente baixados.',
        posthogOptOut: 'Desativar a coleta de dados',
        posthogOptIn: 'Ativar a coleta de dados',
        posthogOptOutConfirmation: 'Desativar a coleta de dados?',
        posthogOptOutConfirmationMessage: 'Isso desativará a coleta de dados. Você pode ativá-la novamente a qualquer momento.',

        preferences: 'Preferências',
        accessibilityAndLanguage: 'ACESSIBILIDADE E LÍNGUA',
        legacyNumberSelection: 'Seleção de Número Antigo',
        language: 'Língua',
        appearance: 'APARÊNCIA',
        theme: 'Tema',
        darkMode: 'Modo Escuro',
        lightMode: 'Modo Claro',
        systemDefault: 'Sistema Padrão',
        other: 'Outro',
        invertSheetMusic: 'Inverter Notação',

        sortingLabel: 'Ordenar por',
        numerical: 'Número',
        alphabetical: 'Alfabético',
        topical: 'Tópico',
        deleteHymnal: 'Deletar Hinário',

        notes: 'Notas',
        piano: 'Piano',
        all: 'Todas',
        removeBookmark: 'Remover Marcador',
        saveBookmark: 'Salvar como Marcador',
        share: 'Compartilhar',
        reportIssue: 'Relatar Problema',
        reportIssueSuccess: 'Problema reportado com sucesso',
        reportIssueFailure: 'Falha ao reportar problema',
        // Hymnal Importer screen
        addHymnalSubtitle: 'Baixe hinários para acessá-los offline.',
        verifying: 'Verificando...',
        size: 'Tamanho',
        progress: 'Progresso',
        failedToLoadHymnals: 'Falha ao carregar os hinários',
        failedToLoadHymnalsMessage: 'Verifique sua conexão com a internet e tente novamente.',
        retry: 'Tentar novamente',
        verificationFailed: 'Verificação falhou',
        verificationFailedMessage: 'Alguns arquivos não puderam ser baixados corretamente. Tente novamente.',
        ok: 'OK',
        startingDownload: 'Iniciando download...',
    }
}

export { supportedLanguages, getLanguageName, translations };